[".config/bat/themes/Eldritch.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/eldritch-theme/bat/refs/heads/master/Eldritch.tmTheme"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".config/ghostty/themes/Eldritch"]
type = "file"
url = "https://raw.githubusercontent.com/eldritch-theme/ghostty/refs/heads/master/Eldritch"
exact = true
stripComponents = 1
refreshPeriod = "168h"
