gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    selectedLineBgColor:
      - white
      - bold
  sidePanelWidth: 0.2
git:
  paging:
    externalDiffCommand: difft --color=always --width $(tput cols) --display=side-by-side-show-both
keybinding:
  universal:
    nextTab: ä
    prevTab: ö
