[bar]
# Base height of the bar in pixels - all other sizes scale from this
size = 32

# Spacing between widgets within each section (in pixels)
spacing = 6

# Distance from the screen edge to the bar window (in pixels)
screen_margin = 4

# Distance from the bar edge to the first/last section (in pixels)
inset = 2

# Border radius for the bar (percentage of bar height, 50% = fully rounded)
border_radius = 0

popover_offset = 7
# background_color = "#323449"
# background_opacity = 1.0

[widgets]
center = ["clock"]
right = ["media", "tray", "quick_settings", "battery", "notifications"]
border_radius = 30
background_color = "#323449"

[widgets.updates]
disabled = true

[widgets.cpu]
disabled = true

[theme]
mode = "auto"
accent = "#37f499"

[theme.states]
success = "#c3e88d"
warning = "#ffc777"
urgent = "#ff757f"

[theme.typography]
font_family = "Hack NF Propo, monospace"
