[bar]
# Base height of the bar in pixels - all other sizes scale from this
size = 32

# Spacing between widgets within each section (in pixels)
spacing = 6

# Distance from the screen edge to the bar window (in pixels)
# screen_margin = 4

# Distance from the bar edge to the first/last section (in pixels)
inset = 4

# Border radius for the bar (percentage of bar height, 50% = fully rounded)
border_radius = 0

popover_offset = 6

[widgets]
center = ["clock"]
right = ["media", "tray", "quick_settings", "battery", "notifications"]
border_radius = 40
background_color = "#1a1b26"

[theme]
mode = "gtk"
accent = "#27a1b9"

[theme.states]
success = "#9ece6a"
warning = "#e0af68"
urgent = "#f7768e"

[theme.typography]
font_family = "Hack NF Propo, monospace"
