gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    selectedLineBgColor:
      - white
      - bold
  sidePanelWidth: 0.2
git:
  pagers:
    - pager: diff-so-fancy
keybinding:
  universal:
    nextTab: ä
    prevTab: ö
